<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6AVT452" failures="1" tests="1" name="Test" time="5.138" errors="0" timestamp="2024-09-14T15:06:44 IST">
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.DataProviders.getData(DataProviders.java:25)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
